package com.springmvc.model;
// Generated 05-jun-2018 16:29:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Telefonos generated by hbm2java
 */
@Entity
@Table(name = "telefonos", catalog = "agenda")
public class Telefonos implements java.io.Serializable {

	private Integer idtelefonos;
	private String telefono;
	private Integer idPersona;

	public Telefonos() {
	}

	public Telefonos(String telefono, Integer idPersona) {
		this.telefono = telefono;
		this.idPersona = idPersona;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtelefonos", unique = true, nullable = false)
	public Integer getIdtelefonos() {
		return this.idtelefonos;
	}

	public void setIdtelefonos(Integer idtelefonos) {
		this.idtelefonos = idtelefonos;
	}

	@Column(name = "telefono", length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "idPersona")
	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

}
